// Auto-generated by bootanimgen.py
// Source MIDI: bootanimation_pro.mid
// Generated: 2026-07-09 07:21:38 UTC

use firmware_core::app::{BootAnimation, BootAnimationApp, BootChange, BootFrame};

pub type BootApp = BootAnimationApp;

pub const fn new() -> BootApp {
    BootAnimationApp::new(&BOOT_ANIMATION)
}

static BOOT_ANIMATION: BootAnimation = BootAnimation {
    frames: &BOOT_FRAMES,
    changes: &BOOT_CHANGES,
    end_tick: 2234,
};

static BOOT_FRAMES: [BootFrame; 207] = [
    BootFrame { tick: 0, count: 1 },
    BootFrame { tick: 31, count: 2 },
    BootFrame { tick: 78, count: 2 },
    BootFrame {
        tick: 119,
        count: 1,
    },
    BootFrame {
        tick: 187,
        count: 1,
    },
    BootFrame {
        tick: 250,
        count: 2,
    },
    BootFrame {
        tick: 312,
        count: 2,
    },
    BootFrame {
        tick: 442,
        count: 4,
    },
    BootFrame {
        tick: 453,
        count: 3,
    },
    BootFrame {
        tick: 458,
        count: 3,
    },
    BootFrame {
        tick: 468,
        count: 9,
    },
    BootFrame {
        tick: 479,
        count: 10,
    },
    BootFrame {
        tick: 489,
        count: 9,
    },
    BootFrame {
        tick: 500,
        count: 9,
    },
    BootFrame {
        tick: 505,
        count: 6,
    },
    BootFrame {
        tick: 510,
        count: 11,
    },
    BootFrame {
        tick: 515,
        count: 6,
    },
    BootFrame {
        tick: 526,
        count: 12,
    },
    BootFrame {
        tick: 531,
        count: 2,
    },
    BootFrame {
        tick: 536,
        count: 12,
    },
    BootFrame {
        tick: 541,
        count: 6,
    },
    BootFrame {
        tick: 546,
        count: 8,
    },
    BootFrame {
        tick: 552,
        count: 14,
    },
    BootFrame {
        tick: 557,
        count: 2,
    },
    BootFrame {
        tick: 562,
        count: 6,
    },
    BootFrame {
        tick: 567,
        count: 6,
    },
    BootFrame {
        tick: 572,
        count: 6,
    },
    BootFrame {
        tick: 578,
        count: 12,
    },
    BootFrame {
        tick: 583,
        count: 8,
    },
    BootFrame {
        tick: 588,
        count: 10,
    },
    BootFrame {
        tick: 593,
        count: 14,
    },
    BootFrame {
        tick: 598,
        count: 6,
    },
    BootFrame {
        tick: 604,
        count: 6,
    },
    BootFrame {
        tick: 609,
        count: 8,
    },
    BootFrame {
        tick: 614,
        count: 8,
    },
    BootFrame {
        tick: 619,
        count: 12,
    },
    BootFrame {
        tick: 625,
        count: 12,
    },
    BootFrame {
        tick: 630,
        count: 4,
    },
    BootFrame {
        tick: 635,
        count: 14,
    },
    BootFrame {
        tick: 640,
        count: 12,
    },
    BootFrame {
        tick: 645,
        count: 4,
    },
    BootFrame {
        tick: 651,
        count: 14,
    },
    BootFrame {
        tick: 656,
        count: 8,
    },
    BootFrame {
        tick: 661,
        count: 4,
    },
    BootFrame {
        tick: 666,
        count: 14,
    },
    BootFrame {
        tick: 671,
        count: 11,
    },
    BootFrame {
        tick: 677,
        count: 10,
    },
    BootFrame {
        tick: 682,
        count: 10,
    },
    BootFrame {
        tick: 687,
        count: 11,
    },
    BootFrame {
        tick: 692,
        count: 4,
    },
    BootFrame {
        tick: 697,
        count: 15,
    },
    BootFrame {
        tick: 703,
        count: 4,
    },
    BootFrame {
        tick: 708,
        count: 8,
    },
    BootFrame {
        tick: 713,
        count: 15,
    },
    BootFrame {
        tick: 718,
        count: 4,
    },
    BootFrame {
        tick: 723,
        count: 8,
    },
    BootFrame {
        tick: 729,
        count: 16,
    },
    BootFrame {
        tick: 734,
        count: 4,
    },
    BootFrame {
        tick: 739,
        count: 8,
    },
    BootFrame {
        tick: 744,
        count: 9,
    },
    BootFrame {
        tick: 750,
        count: 4,
    },
    BootFrame {
        tick: 755,
        count: 8,
    },
    BootFrame {
        tick: 760,
        count: 13,
    },
    BootFrame {
        tick: 765,
        count: 4,
    },
    BootFrame {
        tick: 770,
        count: 8,
    },
    BootFrame {
        tick: 776,
        count: 6,
    },
    BootFrame {
        tick: 781,
        count: 11,
    },
    BootFrame {
        tick: 786,
        count: 8,
    },
    BootFrame {
        tick: 791,
        count: 6,
    },
    BootFrame {
        tick: 796,
        count: 8,
    },
    BootFrame {
        tick: 802,
        count: 4,
    },
    BootFrame {
        tick: 807,
        count: 10,
    },
    BootFrame {
        tick: 812,
        count: 6,
    },
    BootFrame {
        tick: 817,
        count: 8,
    },
    BootFrame {
        tick: 822,
        count: 4,
    },
    BootFrame {
        tick: 828,
        count: 12,
    },
    BootFrame {
        tick: 833,
        count: 8,
    },
    BootFrame {
        tick: 838,
        count: 4,
    },
    BootFrame {
        tick: 843,
        count: 12,
    },
    BootFrame {
        tick: 848,
        count: 4,
    },
    BootFrame {
        tick: 854,
        count: 8,
    },
    BootFrame {
        tick: 859,
        count: 6,
    },
    BootFrame {
        tick: 864,
        count: 10,
    },
    BootFrame {
        tick: 869,
        count: 4,
    },
    BootFrame {
        tick: 875,
        count: 10,
    },
    BootFrame {
        tick: 880,
        count: 6,
    },
    BootFrame {
        tick: 885,
        count: 8,
    },
    BootFrame {
        tick: 890,
        count: 4,
    },
    BootFrame {
        tick: 895,
        count: 6,
    },
    BootFrame {
        tick: 901,
        count: 10,
    },
    BootFrame {
        tick: 906,
        count: 4,
    },
    BootFrame {
        tick: 911,
        count: 10,
    },
    BootFrame {
        tick: 916,
        count: 6,
    },
    BootFrame {
        tick: 921,
        count: 8,
    },
    BootFrame {
        tick: 927,
        count: 4,
    },
    BootFrame {
        tick: 932,
        count: 12,
    },
    BootFrame {
        tick: 937,
        count: 4,
    },
    BootFrame {
        tick: 942,
        count: 4,
    },
    BootFrame {
        tick: 947,
        count: 10,
    },
    BootFrame {
        tick: 953,
        count: 6,
    },
    BootFrame {
        tick: 958,
        count: 8,
    },
    BootFrame {
        tick: 963,
        count: 4,
    },
    BootFrame {
        tick: 968,
        count: 6,
    },
    BootFrame {
        tick: 973,
        count: 10,
    },
    BootFrame {
        tick: 979,
        count: 4,
    },
    BootFrame {
        tick: 984,
        count: 10,
    },
    BootFrame {
        tick: 989,
        count: 6,
    },
    BootFrame {
        tick: 994,
        count: 4,
    },
    BootFrame {
        tick: 1000,
        count: 8,
    },
    BootFrame {
        tick: 1005,
        count: 6,
    },
    BootFrame {
        tick: 1010,
        count: 6,
    },
    BootFrame {
        tick: 1015,
        count: 8,
    },
    BootFrame {
        tick: 1020,
        count: 4,
    },
    BootFrame {
        tick: 1026,
        count: 6,
    },
    BootFrame {
        tick: 1031,
        count: 10,
    },
    BootFrame {
        tick: 1036,
        count: 4,
    },
    BootFrame {
        tick: 1041,
        count: 4,
    },
    BootFrame {
        tick: 1046,
        count: 12,
    },
    BootFrame {
        tick: 1052,
        count: 4,
    },
    BootFrame {
        tick: 1057,
        count: 4,
    },
    BootFrame {
        tick: 1062,
        count: 10,
    },
    BootFrame {
        tick: 1067,
        count: 6,
    },
    BootFrame {
        tick: 1072,
        count: 4,
    },
    BootFrame {
        tick: 1078,
        count: 8,
    },
    BootFrame {
        tick: 1083,
        count: 6,
    },
    BootFrame {
        tick: 1088,
        count: 6,
    },
    BootFrame {
        tick: 1093,
        count: 4,
    },
    BootFrame {
        tick: 1098,
        count: 8,
    },
    BootFrame {
        tick: 1104,
        count: 6,
    },
    BootFrame {
        tick: 1109,
        count: 6,
    },
    BootFrame {
        tick: 1114,
        count: 4,
    },
    BootFrame {
        tick: 1119,
        count: 8,
    },
    BootFrame {
        tick: 1125,
        count: 6,
    },
    BootFrame {
        tick: 1130,
        count: 6,
    },
    BootFrame {
        tick: 1135,
        count: 4,
    },
    BootFrame {
        tick: 1140,
        count: 8,
    },
    BootFrame {
        tick: 1145,
        count: 6,
    },
    BootFrame {
        tick: 1151,
        count: 6,
    },
    BootFrame {
        tick: 1156,
        count: 4,
    },
    BootFrame {
        tick: 1161,
        count: 8,
    },
    BootFrame {
        tick: 1166,
        count: 6,
    },
    BootFrame {
        tick: 1171,
        count: 6,
    },
    BootFrame {
        tick: 1177,
        count: 4,
    },
    BootFrame {
        tick: 1182,
        count: 4,
    },
    BootFrame {
        tick: 1187,
        count: 10,
    },
    BootFrame {
        tick: 1192,
        count: 6,
    },
    BootFrame {
        tick: 1197,
        count: 4,
    },
    BootFrame {
        tick: 1203,
        count: 4,
    },
    BootFrame {
        tick: 1208,
        count: 4,
    },
    BootFrame {
        tick: 1213,
        count: 10,
    },
    BootFrame {
        tick: 1218,
        count: 4,
    },
    BootFrame {
        tick: 1223,
        count: 4,
    },
    BootFrame {
        tick: 1229,
        count: 4,
    },
    BootFrame {
        tick: 1234,
        count: 4,
    },
    BootFrame {
        tick: 1239,
        count: 6,
    },
    BootFrame {
        tick: 1244,
        count: 8,
    },
    BootFrame {
        tick: 1250,
        count: 4,
    },
    BootFrame {
        tick: 1255,
        count: 4,
    },
    BootFrame {
        tick: 1260,
        count: 6,
    },
    BootFrame {
        tick: 1265,
        count: 4,
    },
    BootFrame {
        tick: 1270,
        count: 4,
    },
    BootFrame {
        tick: 1276,
        count: 4,
    },
    BootFrame {
        tick: 1281,
        count: 6,
    },
    BootFrame {
        tick: 1286,
        count: 4,
    },
    BootFrame {
        tick: 1291,
        count: 4,
    },
    BootFrame {
        tick: 1296,
        count: 4,
    },
    BootFrame {
        tick: 1302,
        count: 4,
    },
    BootFrame {
        tick: 1307,
        count: 2,
    },
    BootFrame {
        tick: 1312,
        count: 4,
    },
    BootFrame {
        tick: 1317,
        count: 4,
    },
    BootFrame {
        tick: 1322,
        count: 4,
    },
    BootFrame {
        tick: 1328,
        count: 4,
    },
    BootFrame {
        tick: 1333,
        count: 6,
    },
    BootFrame {
        tick: 1338,
        count: 4,
    },
    BootFrame {
        tick: 1343,
        count: 4,
    },
    BootFrame {
        tick: 1348,
        count: 4,
    },
    BootFrame {
        tick: 1354,
        count: 2,
    },
    BootFrame {
        tick: 1364,
        count: 4,
    },
    BootFrame {
        tick: 1369,
        count: 4,
    },
    BootFrame {
        tick: 1375,
        count: 4,
    },
    BootFrame {
        tick: 1380,
        count: 2,
    },
    BootFrame {
        tick: 1390,
        count: 4,
    },
    BootFrame {
        tick: 1395,
        count: 4,
    },
    BootFrame {
        tick: 1401,
        count: 4,
    },
    BootFrame {
        tick: 1406,
        count: 2,
    },
    BootFrame {
        tick: 1416,
        count: 4,
    },
    BootFrame {
        tick: 1421,
        count: 4,
    },
    BootFrame {
        tick: 1427,
        count: 4,
    },
    BootFrame {
        tick: 1432,
        count: 2,
    },
    BootFrame {
        tick: 1447,
        count: 4,
    },
    BootFrame {
        tick: 1453,
        count: 4,
    },
    BootFrame {
        tick: 1458,
        count: 2,
    },
    BootFrame {
        tick: 1473,
        count: 4,
    },
    BootFrame {
        tick: 1479,
        count: 4,
    },
    BootFrame {
        tick: 1484,
        count: 2,
    },
    BootFrame {
        tick: 1505,
        count: 4,
    },
    BootFrame {
        tick: 1510,
        count: 4,
    },
    BootFrame {
        tick: 1515,
        count: 2,
    },
    BootFrame {
        tick: 1536,
        count: 4,
    },
    BootFrame {
        tick: 1541,
        count: 2,
    },
    BootFrame {
        tick: 1567,
        count: 4,
    },
    BootFrame {
        tick: 1572,
        count: 2,
    },
    BootFrame {
        tick: 1598,
        count: 4,
    },
    BootFrame {
        tick: 1609,
        count: 2,
    },
    BootFrame {
        tick: 1640,
        count: 2,
    },
    BootFrame {
        tick: 1682,
        count: 2,
    },
    BootFrame {
        tick: 1734,
        count: 2,
    },
];

static BOOT_CHANGES: [BootChange; 1272] = [
    BootChange {
        led: 98,
        velocity: 3,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 2,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 1,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 1,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 2,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 3,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 101,
        velocity: 3,
    },
    BootChange {
        led: 98,
        velocity: 3,
    },
    BootChange {
        led: 1,
        velocity: 3,
    },
    BootChange {
        led: 102,
        velocity: 3,
    },
    BootChange {
        led: 97,
        velocity: 3,
    },
    BootChange {
        led: 2,
        velocity: 3,
    },
    BootChange {
        led: 103,
        velocity: 3,
    },
    BootChange {
        led: 96,
        velocity: 3,
    },
    BootChange {
        led: 3,
        velocity: 3,
    },
    BootChange {
        led: 104,
        velocity: 3,
    },
    BootChange {
        led: 95,
        velocity: 3,
    },
    BootChange {
        led: 4,
        velocity: 3,
    },
    BootChange {
        led: 101,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 1,
        velocity: 0,
    },
    BootChange {
        led: 101,
        velocity: 13,
    },
    BootChange {
        led: 98,
        velocity: 13,
    },
    BootChange {
        led: 1,
        velocity: 13,
    },
    BootChange {
        led: 105,
        velocity: 3,
    },
    BootChange {
        led: 99,
        velocity: 3,
    },
    BootChange {
        led: 94,
        velocity: 3,
    },
    BootChange {
        led: 5,
        velocity: 3,
    },
    BootChange {
        led: 102,
        velocity: 0,
    },
    BootChange {
        led: 102,
        velocity: 13,
    },
    BootChange {
        led: 97,
        velocity: 0,
    },
    BootChange {
        led: 97,
        velocity: 13,
    },
    BootChange {
        led: 2,
        velocity: 0,
    },
    BootChange {
        led: 2,
        velocity: 13,
    },
    BootChange {
        led: 106,
        velocity: 3,
    },
    BootChange {
        led: 93,
        velocity: 3,
    },
    BootChange {
        led: 6,
        velocity: 3,
    },
    BootChange {
        led: 103,
        velocity: 0,
    },
    BootChange {
        led: 103,
        velocity: 13,
    },
    BootChange {
        led: 96,
        velocity: 0,
    },
    BootChange {
        led: 96,
        velocity: 13,
    },
    BootChange {
        led: 3,
        velocity: 0,
    },
    BootChange {
        led: 3,
        velocity: 13,
    },
    BootChange {
        led: 107,
        velocity: 3,
    },
    BootChange {
        led: 92,
        velocity: 3,
    },
    BootChange {
        led: 7,
        velocity: 3,
    },
    BootChange {
        led: 104,
        velocity: 0,
    },
    BootChange {
        led: 104,
        velocity: 13,
    },
    BootChange {
        led: 95,
        velocity: 0,
    },
    BootChange {
        led: 95,
        velocity: 13,
    },
    BootChange {
        led: 4,
        velocity: 0,
    },
    BootChange {
        led: 4,
        velocity: 13,
    },
    BootChange {
        led: 101,
        velocity: 0,
    },
    BootChange {
        led: 101,
        velocity: 9,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 9,
    },
    BootChange {
        led: 1,
        velocity: 0,
    },
    BootChange {
        led: 1,
        velocity: 9,
    },
    BootChange {
        led: 108,
        velocity: 3,
    },
    BootChange {
        led: 91,
        velocity: 3,
    },
    BootChange {
        led: 8,
        velocity: 3,
    },
    BootChange {
        led: 105,
        velocity: 0,
    },
    BootChange {
        led: 105,
        velocity: 13,
    },
    BootChange {
        led: 99,
        velocity: 0,
    },
    BootChange {
        led: 99,
        velocity: 13,
    },
    BootChange {
        led: 94,
        velocity: 0,
    },
    BootChange {
        led: 94,
        velocity: 13,
    },
    BootChange {
        led: 5,
        velocity: 0,
    },
    BootChange {
        led: 5,
        velocity: 13,
    },
    BootChange {
        led: 102,
        velocity: 0,
    },
    BootChange {
        led: 102,
        velocity: 9,
    },
    BootChange {
        led: 97,
        velocity: 0,
    },
    BootChange {
        led: 97,
        velocity: 9,
    },
    BootChange {
        led: 2,
        velocity: 0,
    },
    BootChange {
        led: 2,
        velocity: 9,
    },
    BootChange {
        led: 106,
        velocity: 0,
    },
    BootChange {
        led: 106,
        velocity: 13,
    },
    BootChange {
        led: 93,
        velocity: 0,
    },
    BootChange {
        led: 93,
        velocity: 13,
    },
    BootChange {
        led: 6,
        velocity: 0,
    },
    BootChange {
        led: 6,
        velocity: 13,
    },
    BootChange {
        led: 103,
        velocity: 0,
    },
    BootChange {
        led: 103,
        velocity: 9,
    },
    BootChange {
        led: 96,
        velocity: 0,
    },
    BootChange {
        led: 96,
        velocity: 9,
    },
    BootChange {
        led: 3,
        velocity: 0,
    },
    BootChange {
        led: 3,
        velocity: 9,
    },
    BootChange {
        led: 19,
        velocity: 3,
    },
    BootChange {
        led: 80,
        velocity: 3,
    },
    BootChange {
        led: 107,
        velocity: 0,
    },
    BootChange {
        led: 107,
        velocity: 13,
    },
    BootChange {
        led: 92,
        velocity: 0,
    },
    BootChange {
        led: 92,
        velocity: 13,
    },
    BootChange {
        led: 7,
        velocity: 0,
    },
    BootChange {
        led: 7,
        velocity: 13,
    },
    BootChange {
        led: 104,
        velocity: 0,
    },
    BootChange {
        led: 104,
        velocity: 9,
    },
    BootChange {
        led: 95,
        velocity: 0,
    },
    BootChange {
        led: 95,
        velocity: 9,
    },
    BootChange {
        led: 4,
        velocity: 0,
    },
    BootChange {
        led: 4,
        velocity: 9,
    },
    BootChange {
        led: 101,
        velocity: 0,
    },
    BootChange {
        led: 101,
        velocity: 5,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 5,
    },
    BootChange {
        led: 1,
        velocity: 0,
    },
    BootChange {
        led: 1,
        velocity: 5,
    },
    BootChange {
        led: 29,
        velocity: 3,
    },
    BootChange {
        led: 70,
        velocity: 3,
    },
    BootChange {
        led: 108,
        velocity: 0,
    },
    BootChange {
        led: 108,
        velocity: 13,
    },
    BootChange {
        led: 91,
        velocity: 0,
    },
    BootChange {
        led: 91,
        velocity: 13,
    },
    BootChange {
        led: 8,
        velocity: 0,
    },
    BootChange {
        led: 8,
        velocity: 13,
    },
    BootChange {
        led: 105,
        velocity: 0,
    },
    BootChange {
        led: 105,
        velocity: 9,
    },
    BootChange {
        led: 99,
        velocity: 0,
    },
    BootChange {
        led: 99,
        velocity: 9,
    },
    BootChange {
        led: 94,
        velocity: 0,
    },
    BootChange {
        led: 94,
        velocity: 9,
    },
    BootChange {
        led: 5,
        velocity: 0,
    },
    BootChange {
        led: 5,
        velocity: 9,
    },
    BootChange {
        led: 102,
        velocity: 0,
    },
    BootChange {
        led: 102,
        velocity: 5,
    },
    BootChange {
        led: 97,
        velocity: 0,
    },
    BootChange {
        led: 97,
        velocity: 5,
    },
    BootChange {
        led: 2,
        velocity: 0,
    },
    BootChange {
        led: 2,
        velocity: 5,
    },
    BootChange {
        led: 39,
        velocity: 3,
    },
    BootChange {
        led: 60,
        velocity: 3,
    },
    BootChange {
        led: 106,
        velocity: 0,
    },
    BootChange {
        led: 106,
        velocity: 9,
    },
    BootChange {
        led: 93,
        velocity: 0,
    },
    BootChange {
        led: 93,
        velocity: 9,
    },
    BootChange {
        led: 6,
        velocity: 0,
    },
    BootChange {
        led: 6,
        velocity: 9,
    },
    BootChange {
        led: 103,
        velocity: 0,
    },
    BootChange {
        led: 103,
        velocity: 5,
    },
    BootChange {
        led: 96,
        velocity: 0,
    },
    BootChange {
        led: 96,
        velocity: 5,
    },
    BootChange {
        led: 3,
        velocity: 0,
    },
    BootChange {
        led: 3,
        velocity: 5,
    },
    BootChange {
        led: 49,
        velocity: 3,
    },
    BootChange {
        led: 50,
        velocity: 3,
    },
    BootChange {
        led: 19,
        velocity: 0,
    },
    BootChange {
        led: 19,
        velocity: 13,
    },
    BootChange {
        led: 80,
        velocity: 0,
    },
    BootChange {
        led: 80,
        velocity: 13,
    },
    BootChange {
        led: 107,
        velocity: 0,
    },
    BootChange {
        led: 107,
        velocity: 9,
    },
    BootChange {
        led: 92,
        velocity: 0,
    },
    BootChange {
        led: 92,
        velocity: 9,
    },
    BootChange {
        led: 7,
        velocity: 0,
    },
    BootChange {
        led: 7,
        velocity: 9,
    },
    BootChange {
        led: 104,
        velocity: 0,
    },
    BootChange {
        led: 104,
        velocity: 5,
    },
    BootChange {
        led: 95,
        velocity: 0,
    },
    BootChange {
        led: 95,
        velocity: 5,
    },
    BootChange {
        led: 4,
        velocity: 0,
    },
    BootChange {
        led: 4,
        velocity: 5,
    },
    BootChange {
        led: 101,
        velocity: 0,
    },
    BootChange {
        led: 101,
        velocity: 6,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 6,
    },
    BootChange {
        led: 1,
        velocity: 0,
    },
    BootChange {
        led: 1,
        velocity: 6,
    },
    BootChange {
        led: 59,
        velocity: 3,
    },
    BootChange {
        led: 40,
        velocity: 3,
    },
    BootChange {
        led: 29,
        velocity: 0,
    },
    BootChange {
        led: 29,
        velocity: 13,
    },
    BootChange {
        led: 70,
        velocity: 0,
    },
    BootChange {
        led: 70,
        velocity: 13,
    },
    BootChange {
        led: 108,
        velocity: 0,
    },
    BootChange {
        led: 108,
        velocity: 9,
    },
    BootChange {
        led: 91,
        velocity: 0,
    },
    BootChange {
        led: 91,
        velocity: 9,
    },
    BootChange {
        led: 8,
        velocity: 0,
    },
    BootChange {
        led: 8,
        velocity: 9,
    },
    BootChange {
        led: 105,
        velocity: 0,
    },
    BootChange {
        led: 105,
        velocity: 5,
    },
    BootChange {
        led: 99,
        velocity: 0,
    },
    BootChange {
        led: 99,
        velocity: 5,
    },
    BootChange {
        led: 94,
        velocity: 0,
    },
    BootChange {
        led: 94,
        velocity: 5,
    },
    BootChange {
        led: 5,
        velocity: 0,
    },
    BootChange {
        led: 5,
        velocity: 5,
    },
    BootChange {
        led: 102,
        velocity: 0,
    },
    BootChange {
        led: 102,
        velocity: 6,
    },
    BootChange {
        led: 97,
        velocity: 0,
    },
    BootChange {
        led: 97,
        velocity: 6,
    },
    BootChange {
        led: 2,
        velocity: 0,
    },
    BootChange {
        led: 2,
        velocity: 6,
    },
    BootChange {
        led: 69,
        velocity: 3,
    },
    BootChange {
        led: 30,
        velocity: 3,
    },
    BootChange {
        led: 39,
        velocity: 0,
    },
    BootChange {
        led: 39,
        velocity: 13,
    },
    BootChange {
        led: 60,
        velocity: 0,
    },
    BootChange {
        led: 60,
        velocity: 13,
    },
    BootChange {
        led: 106,
        velocity: 0,
    },
    BootChange {
        led: 106,
        velocity: 5,
    },
    BootChange {
        led: 93,
        velocity: 0,
    },
    BootChange {
        led: 93,
        velocity: 5,
    },
    BootChange {
        led: 6,
        velocity: 0,
    },
    BootChange {
        led: 6,
        velocity: 5,
    },
    BootChange {
        led: 103,
        velocity: 0,
    },
    BootChange {
        led: 103,
        velocity: 6,
    },
    BootChange {
        led: 96,
        velocity: 0,
    },
    BootChange {
        led: 96,
        velocity: 6,
    },
    BootChange {
        led: 3,
        velocity: 0,
    },
    BootChange {
        led: 3,
        velocity: 6,
    },
    BootChange {
        led: 79,
        velocity: 3,
    },
    BootChange {
        led: 20,
        velocity: 3,
    },
    BootChange {
        led: 49,
        velocity: 0,
    },
    BootChange {
        led: 49,
        velocity: 13,
    },
    BootChange {
        led: 50,
        velocity: 0,
    },
    BootChange {
        led: 50,
        velocity: 13,
    },
    BootChange {
        led: 19,
        velocity: 0,
    },
    BootChange {
        led: 80,
        velocity: 0,
    },
    BootChange {
        led: 19,
        velocity: 9,
    },
    BootChange {
        led: 80,
        velocity: 9,
    },
    BootChange {
        led: 107,
        velocity: 0,
    },
    BootChange {
        led: 107,
        velocity: 5,
    },
    BootChange {
        led: 92,
        velocity: 0,
    },
    BootChange {
        led: 92,
        velocity: 5,
    },
    BootChange {
        led: 7,
        velocity: 0,
    },
    BootChange {
        led: 7,
        velocity: 5,
    },
    BootChange {
        led: 104,
        velocity: 0,
    },
    BootChange {
        led: 104,
        velocity: 6,
    },
    BootChange {
        led: 95,
        velocity: 0,
    },
    BootChange {
        led: 95,
        velocity: 6,
    },
    BootChange {
        led: 4,
        velocity: 0,
    },
    BootChange {
        led: 4,
        velocity: 6,
    },
    BootChange {
        led: 101,
        velocity: 0,
    },
    BootChange {
        led: 101,
        velocity: 7,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 7,
    },
    BootChange {
        led: 89,
        velocity: 3,
    },
    BootChange {
        led: 10,
        velocity: 3,
    },
    BootChange {
        led: 1,
        velocity: 0,
    },
    BootChange {
        led: 1,
        velocity: 7,
    },
    BootChange {
        led: 59,
        velocity: 0,
    },
    BootChange {
        led: 59,
        velocity: 13,
    },
    BootChange {
        led: 40,
        velocity: 0,
    },
    BootChange {
        led: 40,
        velocity: 13,
    },
    BootChange {
        led: 29,
        velocity: 0,
    },
    BootChange {
        led: 29,
        velocity: 9,
    },
    BootChange {
        led: 70,
        velocity: 0,
    },
    BootChange {
        led: 70,
        velocity: 9,
    },
    BootChange {
        led: 108,
        velocity: 0,
    },
    BootChange {
        led: 108,
        velocity: 5,
    },
    BootChange {
        led: 91,
        velocity: 0,
    },
    BootChange {
        led: 91,
        velocity: 5,
    },
    BootChange {
        led: 8,
        velocity: 0,
    },
    BootChange {
        led: 8,
        velocity: 5,
    },
    BootChange {
        led: 105,
        velocity: 0,
    },
    BootChange {
        led: 105,
        velocity: 6,
    },
    BootChange {
        led: 99,
        velocity: 0,
    },
    BootChange {
        led: 99,
        velocity: 6,
    },
    BootChange {
        led: 94,
        velocity: 0,
    },
    BootChange {
        led: 94,
        velocity: 6,
    },
    BootChange {
        led: 5,
        velocity: 0,
    },
    BootChange {
        led: 5,
        velocity: 6,
    },
    BootChange {
        led: 102,
        velocity: 0,
    },
    BootChange {
        led: 102,
        velocity: 7,
    },
    BootChange {
        led: 97,
        velocity: 0,
    },
    BootChange {
        led: 97,
        velocity: 7,
    },
    BootChange {
        led: 11,
        velocity: 3,
    },
    BootChange {
        led: 88,
        velocity: 3,
    },
    BootChange {
        led: 2,
        velocity: 0,
    },
    BootChange {
        led: 2,
        velocity: 7,
    },
    BootChange {
        led: 69,
        velocity: 0,
    },
    BootChange {
        led: 30,
        velocity: 0,
    },
    BootChange {
        led: 69,
        velocity: 13,
    },
    BootChange {
        led: 30,
        velocity: 13,
    },
    BootChange {
        led: 39,
        velocity: 0,
    },
    BootChange {
        led: 39,
        velocity: 9,
    },
    BootChange {
        led: 60,
        velocity: 0,
    },
    BootChange {
        led: 60,
        velocity: 9,
    },
    BootChange {
        led: 106,
        velocity: 0,
    },
    BootChange {
        led: 106,
        velocity: 6,
    },
    BootChange {
        led: 93,
        velocity: 0,
    },
    BootChange {
        led: 93,
        velocity: 6,
    },
    BootChange {
        led: 6,
        velocity: 0,
    },
    BootChange {
        led: 6,
        velocity: 6,
    },
    BootChange {
        led: 103,
        velocity: 0,
    },
    BootChange {
        led: 96,
        velocity: 0,
    },
    BootChange {
        led: 3,
        velocity: 0,
    },
    BootChange {
        led: 103,
        velocity: 7,
    },
    BootChange {
        led: 96,
        velocity: 7,
    },
    BootChange {
        led: 12,
        velocity: 3,
    },
    BootChange {
        led: 87,
        velocity: 3,
    },
    BootChange {
        led: 3,
        velocity: 7,
    },
    BootChange {
        led: 79,
        velocity: 0,
    },
    BootChange {
        led: 79,
        velocity: 13,
    },
    BootChange {
        led: 20,
        velocity: 0,
    },
    BootChange {
        led: 20,
        velocity: 13,
    },
    BootChange {
        led: 49,
        velocity: 0,
    },
    BootChange {
        led: 49,
        velocity: 9,
    },
    BootChange {
        led: 50,
        velocity: 0,
    },
    BootChange {
        led: 50,
        velocity: 9,
    },
    BootChange {
        led: 19,
        velocity: 0,
    },
    BootChange {
        led: 19,
        velocity: 5,
    },
    BootChange {
        led: 80,
        velocity: 0,
    },
    BootChange {
        led: 80,
        velocity: 5,
    },
    BootChange {
        led: 107,
        velocity: 0,
    },
    BootChange {
        led: 107,
        velocity: 6,
    },
    BootChange {
        led: 92,
        velocity: 0,
    },
    BootChange {
        led: 92,
        velocity: 6,
    },
    BootChange {
        led: 7,
        velocity: 0,
    },
    BootChange {
        led: 7,
        velocity: 6,
    },
    BootChange {
        led: 104,
        velocity: 0,
    },
    BootChange {
        led: 104,
        velocity: 7,
    },
    BootChange {
        led: 95,
        velocity: 0,
    },
    BootChange {
        led: 95,
        velocity: 7,
    },
    BootChange {
        led: 13,
        velocity: 3,
    },
    BootChange {
        led: 86,
        velocity: 3,
    },
    BootChange {
        led: 4,
        velocity: 0,
    },
    BootChange {
        led: 4,
        velocity: 7,
    },
    BootChange {
        led: 101,
        velocity: 0,
    },
    BootChange {
        led: 98,
        velocity: 0,
    },
    BootChange {
        led: 89,
        velocity: 0,
    },
    BootChange {
        led: 89,
        velocity: 13,
    },
    BootChange {
        led: 10,
        velocity: 0,
    },
    BootChange {
        led: 10,
        velocity: 13,
    },
    BootChange {
        led: 1,
        velocity: 0,
    },
    BootChange {
        led: 59,
        velocity: 0,
    },
    BootChange {
        led: 59,
        velocity: 9,
    },
    BootChange {
        led: 40,
        velocity: 0,
    },
    BootChange {
        led: 40,
        velocity: 9,
    },
    BootChange {
        led: 29,
        velocity: 0,
    },
    BootChange {
        led: 29,
        velocity: 5,
    },
    BootChange {
        led: 70,
        velocity: 0,
    },
    BootChange {
        led: 70,
        velocity: 5,
    },
    BootChange {
        led: 108,
        velocity: 0,
    },
    BootChange {
        led: 108,
        velocity: 6,
    },
    BootChange {
        led: 91,
        velocity: 0,
    },
    BootChange {
        led: 91,
        velocity: 6,
    },
    BootChange {
        led: 8,
        velocity: 0,
    },
    BootChange {
        led: 8,
        velocity: 6,
    },
    BootChange {
        led: 105,
        velocity: 0,
    },
    BootChange {
        led: 99,
        velocity: 0,
    },
    BootChange {
        led: 94,
        velocity: 0,
    },
    BootChange {
        led: 5,
        velocity: 0,
    },
    BootChange {
        led: 105,
        velocity: 7,
    },
    BootChange {
        led: 99,
        velocity: 7,
    },
    BootChange {
        led: 94,
        velocity: 7,
    },
    BootChange {
        led: 14,
        velocity: 3,
    },
    BootChange {
        led: 85,
        velocity: 3,
    },
    BootChange {
        led: 5,
        velocity: 7,
    },
    BootChange {
        led: 102,
        velocity: 0,
    },
    BootChange {
        led: 97,
        velocity: 0,
    },
    BootChange {
        led: 11,
        velocity: 0,
    },
    BootChange {
        led: 11,
        velocity: 13,
    },
    BootChange {
        led: 88,
        velocity: 0,
    },
    BootChange {
        led: 88,
        velocity: 13,
    },
    BootChange {
        led: 2,
        velocity: 0,
    },
    BootChange {
        led: 69,
        velocity: 0,
    },
    BootChange {
        led: 69,
        velocity: 9,
    },
    BootChange {
        led: 30,
        velocity: 0,
    },
    BootChange {
        led: 30,
        velocity: 9,
    },
    BootChange {
        led: 39,
        velocity: 0,
    },
    BootChange {
        led: 39,
        velocity: 5,
    },
    BootChange {
        led: 60,
        velocity: 0,
    },
    BootChange {
        led: 60,
        velocity: 5,
    },
    BootChange {
        led: 106,
        velocity: 0,
    },
    BootChange {
        led: 106,
        velocity: 7,
    },
    BootChange {
        led: 93,
        velocity: 0,
    },
    BootChange {
        led: 93,
        velocity: 7,
    },
    BootChange {
        led: 84,
        velocity: 3,
    },
    BootChange {
        led: 15,
        velocity: 3,
    },
    BootChange {
        led: 6,
        velocity: 0,
    },
    BootChange {
        led: 6,
        velocity: 7,
    },
    BootChange {
        led: 103,
        velocity: 0,
    },
    BootChange {
        led: 96,
        velocity: 0,
    },
    BootChange {
        led: 12,
        velocity: 0,
    },
    BootChange {
        led: 12,
        velocity: 13,
    },
    BootChange {
        led: 87,
        velocity: 0,
    },
    BootChange {
        led: 87,
        velocity: 13,
    },
    BootChange {
        led: 3,
        velocity: 0,
    },
    BootChange {
        led: 79,
        velocity: 0,
    },
    BootChange {
        led: 79,
        velocity: 9,
    },
    BootChange {
        led: 20,
        velocity: 0,
    },
    BootChange {
        led: 20,
        velocity: 9,
    },
    BootChange {
        led: 49,
        velocity: 0,
    },
    BootChange {
        led: 49,
        velocity: 5,
    },
    BootChange {
        led: 50,
        velocity: 0,
    },
    BootChange {
        led: 50,
        velocity: 5,
    },
    BootChange {
        led: 19,
        velocity: 0,
    },
    BootChange {
        led: 80,
        velocity: 0,
    },
    BootChange {
        led: 19,
        velocity: 6,
    },
    BootChange {
        led: 80,
        velocity: 6,
    },
    BootChange {
        led: 107,
        velocity: 0,
    },
    BootChange {
        led: 107,
        velocity: 7,
    },
    BootChange {
        led: 92,
        velocity: 0,
    },
    BootChange {
        led: 92,
        velocity: 7,
    },
    BootChange {
        led: 83,
        velocity: 3,
    },
    BootChange {
        led: 16,
        velocity: 3,
    },
    BootChange {
        led: 7,
        velocity: 0,
    },
    BootChange {
        led: 7,
        velocity: 7,
    },
    BootChange {
        led: 104,
        velocity: 0,
    },
    BootChange {
        led: 95,
        velocity: 0,
    },
    BootChange {
        led: 13,
        velocity: 0,
    },
    BootChange {
        led: 13,
        velocity: 13,
    },
    BootChange {
        led: 86,
        velocity: 0,
    },
    BootChange {
        led: 86,
        velocity: 13,
    },
    BootChange {
        led: 4,
        velocity: 0,
    },
    BootChange {
        led: 89,
        velocity: 0,
    },
    BootChange {
        led: 89,
        velocity: 9,
    },
    BootChange {
        led: 10,
        velocity: 0,
    },
    BootChange {
        led: 10,
        velocity: 9,
    },
    BootChange {
        led: 59,
        velocity: 0,
    },
    BootChange {
        led: 59,
        velocity: 5,
    },
    BootChange {
        led: 40,
        velocity: 0,
    },
    BootChange {
        led: 40,
        velocity: 5,
    },
    BootChange {
        led: 29,
        velocity: 0,
    },
    BootChange {
        led: 29,
        velocity: 6,
    },
    BootChange {
        led: 70,
        velocity: 0,
    },
    BootChange {
        led: 70,
        velocity: 6,
    },
    BootChange {
        led: 108,
        velocity: 0,
    },
    BootChange {
        led: 108,
        velocity: 7,
    },
    BootChange {
        led: 91,
        velocity: 0,
    },
    BootChange {
        led: 91,
        velocity: 7,
    },
    BootChange {
        led: 82,
        velocity: 3,
    },
    BootChange {
        led: 17,
        velocity: 3,
    },
    BootChange {
        led: 8,
        velocity: 0,
    },
    BootChange {
        led: 8,
        velocity: 7,
    },
    BootChange {
        led: 105,
        velocity: 0,
    },
    BootChange {
        led: 99,
        velocity: 0,
    },
    BootChange {
        led: 94,
        velocity: 0,
    },
    BootChange {
        led: 14,
        velocity: 0,
    },
    BootChange {
        led: 14,
        velocity: 13,
    },
    BootChange {
        led: 85,
        velocity: 0,
    },
    BootChange {
        led: 85,
        velocity: 13,
    },
    BootChange {
        led: 5,
        velocity: 0,
    },
    BootChange {
        led: 11,
        velocity: 0,
    },
    BootChange {
        led: 11,
        velocity: 9,
    },
    BootChange {
        led: 88,
        velocity: 0,
    },
    BootChange {
        led: 88,
        velocity: 9,
    },
    BootChange {
        led: 69,
        velocity: 0,
    },
    BootChange {
        led: 69,
        velocity: 5,
    },
    BootChange {
        led: 30,
        velocity: 0,
    },
    BootChange {
        led: 30,
        velocity: 5,
    },
    BootChange {
        led: 39,
        velocity: 0,
    },
    BootChange {
        led: 39,
        velocity: 6,
    },
    BootChange {
        led: 60,
        velocity: 0,
    },
    BootChange {
        led: 60,
        velocity: 6,
    },
    BootChange {
        led: 81,
        velocity: 3,
    },
    BootChange {
        led: 18,
        velocity: 3,
    },
    BootChange {
        led: 106,
        velocity: 0,
    },
    BootChange {
        led: 93,
        velocity: 0,
    },
    BootChange {
        led: 84,
        velocity: 0,
    },
    BootChange {
        led: 15,
        velocity: 0,
    },
    BootChange {
        led: 6,
        velocity: 0,
    },
    BootChange {
        led: 84,
        velocity: 13,
    },
    BootChange {
        led: 15,
        velocity: 13,
    },
    BootChange {
        led: 12,
        velocity: 0,
    },
    BootChange {
        led: 12,
        velocity: 9,
    },
    BootChange {
        led: 87,
        velocity: 0,
    },
    BootChange {
        led: 87,
        velocity: 9,
    },
    BootChange {
        led: 79,
        velocity: 0,
    },
    BootChange {
        led: 79,
        velocity: 5,
    },
    BootChange {
        led: 20,
        velocity: 0,
    },
    BootChange {
        led: 20,
        velocity: 5,
    },
    BootChange {
        led: 49,
        velocity: 0,
    },
    BootChange {
        led: 49,
        velocity: 6,
    },
    BootChange {
        led: 50,
        velocity: 0,
    },
    BootChange {
        led: 50,
        velocity: 6,
    },
    BootChange {
        led: 71,
        velocity: 3,
    },
    BootChange {
        led: 28,
        velocity: 3,
    },
    BootChange {
        led: 19,
        velocity: 0,
    },
    BootChange {
        led: 19,
        velocity: 7,
    },
    BootChange {
        led: 80,
        velocity: 0,
    },
    BootChange {
        led: 80,
        velocity: 7,
    },
    BootChange {
        led: 107,
        velocity: 0,
    },
    BootChange {
        led: 92,
        velocity: 0,
    },
    BootChange {
        led: 83,
        velocity: 0,
    },
    BootChange {
        led: 16,
        velocity: 0,
    },
    BootChange {
        led: 7,
        velocity: 0,
    },
    BootChange {
        led: 83,
        velocity: 13,
    },
    BootChange {
        led: 16,
        velocity: 13,
    },
    BootChange {
        led: 13,
        velocity: 0,
    },
    BootChange {
        led: 13,
        velocity: 9,
    },
    BootChange {
        led: 86,
        velocity: 0,
    },
    BootChange {
        led: 86,
        velocity: 9,
    },
    BootChange {
        led: 89,
        velocity: 0,
    },
    BootChange {
        led: 89,
        velocity: 5,
    },
    BootChange {
        led: 10,
        velocity: 0,
    },
    BootChange {
        led: 10,
        velocity: 5,
    },
    BootChange {
        led: 59,
        velocity: 0,
    },
    BootChange {
        led: 59,
        velocity: 6,
    },
    BootChange {
        led: 40,
        velocity: 0,
    },
    BootChange {
        led: 40,
        velocity: 6,
    },
    BootChange {
        led: 61,
        velocity: 3,
    },
    BootChange {
        led: 38,
        velocity: 3,
    },
    BootChange {
        led: 29,
        velocity: 0,
    },
    BootChange {
        led: 29,
        velocity: 7,
    },
    BootChange {
        led: 70,
        velocity: 0,
    },
    BootChange {
        led: 70,
        velocity: 7,
    },
    BootChange {
        led: 108,
        velocity: 0,
    },
    BootChange {
        led: 91,
        velocity: 0,
    },
    BootChange {
        led: 82,
        velocity: 0,
    },
    BootChange {
        led: 17,
        velocity: 0,
    },
    BootChange {
        led: 8,
        velocity: 0,
    },
    BootChange {
        led: 82,
        velocity: 13,
    },
    BootChange {
        led: 17,
        velocity: 13,
    },
    BootChange {
        led: 14,
        velocity: 0,
    },
    BootChange {
        led: 14,
        velocity: 9,
    },
    BootChange {
        led: 85,
        velocity: 0,
    },
    BootChange {
        led: 85,
        velocity: 9,
    },
    BootChange {
        led: 11,
        velocity: 0,
    },
    BootChange {
        led: 11,
        velocity: 5,
    },
    BootChange {
        led: 88,
        velocity: 0,
    },
    BootChange {
        led: 88,
        velocity: 5,
    },
    BootChange {
        led: 69,
        velocity: 0,
    },
    BootChange {
        led: 69,
        velocity: 6,
    },
    BootChange {
        led: 30,
        velocity: 0,
    },
    BootChange {
        led: 30,
        velocity: 6,
    },
    BootChange {
        led: 51,
        velocity: 3,
    },
    BootChange {
        led: 48,
        velocity: 3,
    },
    BootChange {
        led: 39,
        velocity: 0,
    },
    BootChange {
        led: 39,
        velocity: 7,
    },
    BootChange {
        led: 60,
        velocity: 0,
    },
    BootChange {
        led: 60,
        velocity: 7,
    },
    BootChange {
        led: 81,
        velocity: 0,
    },
    BootChange {
        led: 81,
        velocity: 13,
    },
    BootChange {
        led: 18,
        velocity: 0,
    },
    BootChange {
        led: 18,
        velocity: 13,
    },
    BootChange {
        led: 84,
        velocity: 0,
    },
    BootChange {
        led: 84,
        velocity: 9,
    },
    BootChange {
        led: 15,
        velocity: 0,
    },
    BootChange {
        led: 15,
        velocity: 9,
    },
    BootChange {
        led: 12,
        velocity: 0,
    },
    BootChange {
        led: 12,
        velocity: 5,
    },
    BootChange {
        led: 87,
        velocity: 0,
    },
    BootChange {
        led: 87,
        velocity: 5,
    },
    BootChange {
        led: 79,
        velocity: 0,
    },
    BootChange {
        led: 79,
        velocity: 6,
    },
    BootChange {
        led: 20,
        velocity: 0,
    },
    BootChange {
        led: 20,
        velocity: 6,
    },
    BootChange {
        led: 41,
        velocity: 3,
    },
    BootChange {
        led: 58,
        velocity: 3,
    },
    BootChange {
        led: 49,
        velocity: 0,
    },
    BootChange {
        led: 49,
        velocity: 7,
    },
    BootChange {
        led: 50,
        velocity: 0,
    },
    BootChange {
        led: 50,
        velocity: 7,
    },
    BootChange {
        led: 71,
        velocity: 0,
    },
    BootChange {
        led: 71,
        velocity: 13,
    },
    BootChange {
        led: 28,
        velocity: 0,
    },
    BootChange {
        led: 28,
        velocity: 13,
    },
    BootChange {
        led: 19,
        velocity: 0,
    },
    BootChange {
        led: 80,
        velocity: 0,
    },
    BootChange {
        led: 83,
        velocity: 0,
    },
    BootChange {
        led: 83,
        velocity: 9,
    },
    BootChange {
        led: 16,
        velocity: 0,
    },
    BootChange {
        led: 16,
        velocity: 9,
    },
    BootChange {
        led: 13,
        velocity: 0,
    },
    BootChange {
        led: 13,
        velocity: 5,
    },
    BootChange {
        led: 86,
        velocity: 0,
    },
    BootChange {
        led: 86,
        velocity: 5,
    },
    BootChange {
        led: 89,
        velocity: 0,
    },
    BootChange {
        led: 89,
        velocity: 6,
    },
    BootChange {
        led: 10,
        velocity: 0,
    },
    BootChange {
        led: 10,
        velocity: 6,
    },
    BootChange {
        led: 31,
        velocity: 3,
    },
    BootChange {
        led: 68,
        velocity: 3,
    },
    BootChange {
        led: 59,
        velocity: 0,
    },
    BootChange {
        led: 59,
        velocity: 7,
    },
    BootChange {
        led: 40,
        velocity: 0,
    },
    BootChange {
        led: 40,
        velocity: 7,
    },
    BootChange {
        led: 61,
        velocity: 0,
    },
    BootChange {
        led: 61,
        velocity: 13,
    },
    BootChange {
        led: 38,
        velocity: 0,
    },
    BootChange {
        led: 38,
        velocity: 13,
    },
    BootChange {
        led: 29,
        velocity: 0,
    },
    BootChange {
        led: 70,
        velocity: 0,
    },
    BootChange {
        led: 82,
        velocity: 0,
    },
    BootChange {
        led: 82,
        velocity: 9,
    },
    BootChange {
        led: 17,
        velocity: 0,
    },
    BootChange {
        led: 17,
        velocity: 9,
    },
    BootChange {
        led: 14,
        velocity: 0,
    },
    BootChange {
        led: 14,
        velocity: 5,
    },
    BootChange {
        led: 85,
        velocity: 0,
    },
    BootChange {
        led: 85,
        velocity: 5,
    },
    BootChange {
        led: 11,
        velocity: 0,
    },
    BootChange {
        led: 11,
        velocity: 6,
    },
    BootChange {
        led: 88,
        velocity: 0,
    },
    BootChange {
        led: 88,
        velocity: 6,
    },
    BootChange {
        led: 21,
        velocity: 3,
    },
    BootChange {
        led: 78,
        velocity: 3,
    },
    BootChange {
        led: 69,
        velocity: 0,
    },
    BootChange {
        led: 69,
        velocity: 7,
    },
    BootChange {
        led: 30,
        velocity: 0,
    },
    BootChange {
        led: 30,
        velocity: 7,
    },
    BootChange {
        led: 51,
        velocity: 0,
    },
    BootChange {
        led: 51,
        velocity: 13,
    },
    BootChange {
        led: 48,
        velocity: 0,
    },
    BootChange {
        led: 48,
        velocity: 13,
    },
    BootChange {
        led: 39,
        velocity: 0,
    },
    BootChange {
        led: 60,
        velocity: 0,
    },
    BootChange {
        led: 81,
        velocity: 0,
    },
    BootChange {
        led: 81,
        velocity: 9,
    },
    BootChange {
        led: 18,
        velocity: 0,
    },
    BootChange {
        led: 18,
        velocity: 9,
    },
    BootChange {
        led: 84,
        velocity: 0,
    },
    BootChange {
        led: 84,
        velocity: 5,
    },
    BootChange {
        led: 15,
        velocity: 0,
    },
    BootChange {
        led: 15,
        velocity: 5,
    },
    BootChange {
        led: 12,
        velocity: 0,
    },
    BootChange {
        led: 12,
        velocity: 6,
    },
    BootChange {
        led: 87,
        velocity: 0,
    },
    BootChange {
        led: 87,
        velocity: 6,
    },
    BootChange {
        led: 22,
        velocity: 3,
    },
    BootChange {
        led: 77,
        velocity: 3,
    },
    BootChange {
        led: 79,
        velocity: 0,
    },
    BootChange {
        led: 79,
        velocity: 7,
    },
    BootChange {
        led: 20,
        velocity: 0,
    },
    BootChange {
        led: 20,
        velocity: 7,
    },
    BootChange {
        led: 41,
        velocity: 0,
    },
    BootChange {
        led: 41,
        velocity: 13,
    },
    BootChange {
        led: 58,
        velocity: 0,
    },
    BootChange {
        led: 58,
        velocity: 13,
    },
    BootChange {
        led: 49,
        velocity: 0,
    },
    BootChange {
        led: 50,
        velocity: 0,
    },
    BootChange {
        led: 71,
        velocity: 0,
    },
    BootChange {
        led: 71,
        velocity: 9,
    },
    BootChange {
        led: 28,
        velocity: 0,
    },
    BootChange {
        led: 28,
        velocity: 9,
    },
    BootChange {
        led: 83,
        velocity: 0,
    },
    BootChange {
        led: 83,
        velocity: 5,
    },
    BootChange {
        led: 16,
        velocity: 0,
    },
    BootChange {
        led: 16,
        velocity: 5,
    },
    BootChange {
        led: 13,
        velocity: 0,
    },
    BootChange {
        led: 13,
        velocity: 6,
    },
    BootChange {
        led: 86,
        velocity: 0,
    },
    BootChange {
        led: 86,
        velocity: 6,
    },
    BootChange {
        led: 23,
        velocity: 3,
    },
    BootChange {
        led: 76,
        velocity: 3,
    },
    BootChange {
        led: 89,
        velocity: 0,
    },
    BootChange {
        led: 89,
        velocity: 7,
    },
    BootChange {
        led: 10,
        velocity: 0,
    },
    BootChange {
        led: 10,
        velocity: 7,
    },
    BootChange {
        led: 31,
        velocity: 0,
    },
    BootChange {
        led: 31,
        velocity: 13,
    },
    BootChange {
        led: 68,
        velocity: 0,
    },
    BootChange {
        led: 68,
        velocity: 13,
    },
    BootChange {
        led: 59,
        velocity: 0,
    },
    BootChange {
        led: 40,
        velocity: 0,
    },
    BootChange {
        led: 61,
        velocity: 0,
    },
    BootChange {
        led: 61,
        velocity: 9,
    },
    BootChange {
        led: 38,
        velocity: 0,
    },
    BootChange {
        led: 38,
        velocity: 9,
    },
    BootChange {
        led: 82,
        velocity: 0,
    },
    BootChange {
        led: 82,
        velocity: 5,
    },
    BootChange {
        led: 17,
        velocity: 0,
    },
    BootChange {
        led: 17,
        velocity: 5,
    },
    BootChange {
        led: 14,
        velocity: 0,
    },
    BootChange {
        led: 14,
        velocity: 6,
    },
    BootChange {
        led: 85,
        velocity: 0,
    },
    BootChange {
        led: 85,
        velocity: 6,
    },
    BootChange {
        led: 11,
        velocity: 0,
    },
    BootChange {
        led: 11,
        velocity: 7,
    },
    BootChange {
        led: 24,
        velocity: 3,
    },
    BootChange {
        led: 75,
        velocity: 3,
    },
    BootChange {
        led: 88,
        velocity: 0,
    },
    BootChange {
        led: 88,
        velocity: 7,
    },
    BootChange {
        led: 21,
        velocity: 0,
    },
    BootChange {
        led: 21,
        velocity: 13,
    },
    BootChange {
        led: 78,
        velocity: 0,
    },
    BootChange {
        led: 78,
        velocity: 13,
    },
    BootChange {
        led: 69,
        velocity: 0,
    },
    BootChange {
        led: 30,
        velocity: 0,
    },
    BootChange {
        led: 51,
        velocity: 0,
    },
    BootChange {
        led: 51,
        velocity: 9,
    },
    BootChange {
        led: 48,
        velocity: 0,
    },
    BootChange {
        led: 48,
        velocity: 9,
    },
    BootChange {
        led: 81,
        velocity: 0,
    },
    BootChange {
        led: 81,
        velocity: 5,
    },
    BootChange {
        led: 18,
        velocity: 0,
    },
    BootChange {
        led: 18,
        velocity: 5,
    },
    BootChange {
        led: 84,
        velocity: 0,
    },
    BootChange {
        led: 84,
        velocity: 6,
    },
    BootChange {
        led: 15,
        velocity: 0,
    },
    BootChange {
        led: 15,
        velocity: 6,
    },
    BootChange {
        led: 12,
        velocity: 0,
    },
    BootChange {
        led: 12,
        velocity: 7,
    },
    BootChange {
        led: 74,
        velocity: 3,
    },
    BootChange {
        led: 25,
        velocity: 3,
    },
    BootChange {
        led: 87,
        velocity: 0,
    },
    BootChange {
        led: 87,
        velocity: 7,
    },
    BootChange {
        led: 22,
        velocity: 0,
    },
    BootChange {
        led: 22,
        velocity: 13,
    },
    BootChange {
        led: 77,
        velocity: 0,
    },
    BootChange {
        led: 77,
        velocity: 13,
    },
    BootChange {
        led: 79,
        velocity: 0,
    },
    BootChange {
        led: 20,
        velocity: 0,
    },
    BootChange {
        led: 41,
        velocity: 0,
    },
    BootChange {
        led: 41,
        velocity: 9,
    },
    BootChange {
        led: 58,
        velocity: 0,
    },
    BootChange {
        led: 58,
        velocity: 9,
    },
    BootChange {
        led: 71,
        velocity: 0,
    },
    BootChange {
        led: 71,
        velocity: 5,
    },
    BootChange {
        led: 28,
        velocity: 0,
    },
    BootChange {
        led: 28,
        velocity: 5,
    },
    BootChange {
        led: 83,
        velocity: 0,
    },
    BootChange {
        led: 16,
        velocity: 0,
    },
    BootChange {
        led: 83,
        velocity: 6,
    },
    BootChange {
        led: 16,
        velocity: 6,
    },
    BootChange {
        led: 13,
        velocity: 0,
    },
    BootChange {
        led: 13,
        velocity: 7,
    },
    BootChange {
        led: 73,
        velocity: 3,
    },
    BootChange {
        led: 26,
        velocity: 3,
    },
    BootChange {
        led: 86,
        velocity: 0,
    },
    BootChange {
        led: 86,
        velocity: 7,
    },
    BootChange {
        led: 23,
        velocity: 0,
    },
    BootChange {
        led: 23,
        velocity: 13,
    },
    BootChange {
        led: 76,
        velocity: 0,
    },
    BootChange {
        led: 76,
        velocity: 13,
    },
    BootChange {
        led: 89,
        velocity: 0,
    },
    BootChange {
        led: 10,
        velocity: 0,
    },
    BootChange {
        led: 31,
        velocity: 0,
    },
    BootChange {
        led: 31,
        velocity: 9,
    },
    BootChange {
        led: 68,
        velocity: 0,
    },
    BootChange {
        led: 68,
        velocity: 9,
    },
    BootChange {
        led: 61,
        velocity: 0,
    },
    BootChange {
        led: 61,
        velocity: 5,
    },
    BootChange {
        led: 38,
        velocity: 0,
    },
    BootChange {
        led: 38,
        velocity: 5,
    },
    BootChange {
        led: 82,
        velocity: 0,
    },
    BootChange {
        led: 82,
        velocity: 6,
    },
    BootChange {
        led: 17,
        velocity: 0,
    },
    BootChange {
        led: 17,
        velocity: 6,
    },
    BootChange {
        led: 14,
        velocity: 0,
    },
    BootChange {
        led: 14,
        velocity: 7,
    },
    BootChange {
        led: 72,
        velocity: 3,
    },
    BootChange {
        led: 27,
        velocity: 3,
    },
    BootChange {
        led: 85,
        velocity: 0,
    },
    BootChange {
        led: 85,
        velocity: 7,
    },
    BootChange {
        led: 11,
        velocity: 0,
    },
    BootChange {
        led: 24,
        velocity: 0,
    },
    BootChange {
        led: 24,
        velocity: 13,
    },
    BootChange {
        led: 75,
        velocity: 0,
    },
    BootChange {
        led: 75,
        velocity: 13,
    },
    BootChange {
        led: 88,
        velocity: 0,
    },
    BootChange {
        led: 21,
        velocity: 0,
    },
    BootChange {
        led: 21,
        velocity: 9,
    },
    BootChange {
        led: 78,
        velocity: 0,
    },
    BootChange {
        led: 78,
        velocity: 9,
    },
    BootChange {
        led: 51,
        velocity: 0,
    },
    BootChange {
        led: 51,
        velocity: 5,
    },
    BootChange {
        led: 48,
        velocity: 0,
    },
    BootChange {
        led: 48,
        velocity: 5,
    },
    BootChange {
        led: 81,
        velocity: 0,
    },
    BootChange {
        led: 81,
        velocity: 6,
    },
    BootChange {
        led: 18,
        velocity: 0,
    },
    BootChange {
        led: 18,
        velocity: 6,
    },
    BootChange {
        led: 62,
        velocity: 3,
    },
    BootChange {
        led: 84,
        velocity: 0,
    },
    BootChange {
        led: 84,
        velocity: 7,
    },
    BootChange {
        led: 15,
        velocity: 0,
    },
    BootChange {
        led: 15,
        velocity: 7,
    },
    BootChange {
        led: 37,
        velocity: 3,
    },
    BootChange {
        led: 12,
        velocity: 0,
    },
    BootChange {
        led: 74,
        velocity: 0,
    },
    BootChange {
        led: 74,
        velocity: 13,
    },
    BootChange {
        led: 25,
        velocity: 0,
    },
    BootChange {
        led: 25,
        velocity: 13,
    },
    BootChange {
        led: 87,
        velocity: 0,
    },
    BootChange {
        led: 22,
        velocity: 0,
    },
    BootChange {
        led: 22,
        velocity: 9,
    },
    BootChange {
        led: 77,
        velocity: 0,
    },
    BootChange {
        led: 77,
        velocity: 9,
    },
    BootChange {
        led: 41,
        velocity: 0,
    },
    BootChange {
        led: 41,
        velocity: 5,
    },
    BootChange {
        led: 58,
        velocity: 0,
    },
    BootChange {
        led: 58,
        velocity: 5,
    },
    BootChange {
        led: 71,
        velocity: 0,
    },
    BootChange {
        led: 71,
        velocity: 6,
    },
    BootChange {
        led: 28,
        velocity: 0,
    },
    BootChange {
        led: 28,
        velocity: 6,
    },
    BootChange {
        led: 52,
        velocity: 3,
    },
    BootChange {
        led: 83,
        velocity: 0,
    },
    BootChange {
        led: 83,
        velocity: 7,
    },
    BootChange {
        led: 16,
        velocity: 0,
    },
    BootChange {
        led: 16,
        velocity: 7,
    },
    BootChange {
        led: 47,
        velocity: 3,
    },
    BootChange {
        led: 13,
        velocity: 0,
    },
    BootChange {
        led: 73,
        velocity: 0,
    },
    BootChange {
        led: 73,
        velocity: 13,
    },
    BootChange {
        led: 26,
        velocity: 0,
    },
    BootChange {
        led: 26,
        velocity: 13,
    },
    BootChange {
        led: 86,
        velocity: 0,
    },
    BootChange {
        led: 23,
        velocity: 0,
    },
    BootChange {
        led: 23,
        velocity: 9,
    },
    BootChange {
        led: 76,
        velocity: 0,
    },
    BootChange {
        led: 76,
        velocity: 9,
    },
    BootChange {
        led: 31,
        velocity: 0,
    },
    BootChange {
        led: 31,
        velocity: 5,
    },
    BootChange {
        led: 68,
        velocity: 0,
    },
    BootChange {
        led: 68,
        velocity: 5,
    },
    BootChange {
        led: 61,
        velocity: 0,
    },
    BootChange {
        led: 61,
        velocity: 6,
    },
    BootChange {
        led: 38,
        velocity: 0,
    },
    BootChange {
        led: 38,
        velocity: 6,
    },
    BootChange {
        led: 42,
        velocity: 3,
    },
    BootChange {
        led: 82,
        velocity: 0,
    },
    BootChange {
        led: 82,
        velocity: 7,
    },
    BootChange {
        led: 17,
        velocity: 0,
    },
    BootChange {
        led: 17,
        velocity: 7,
    },
    BootChange {
        led: 57,
        velocity: 3,
    },
    BootChange {
        led: 14,
        velocity: 0,
    },
    BootChange {
        led: 72,
        velocity: 0,
    },
    BootChange {
        led: 72,
        velocity: 13,
    },
    BootChange {
        led: 27,
        velocity: 0,
    },
    BootChange {
        led: 27,
        velocity: 13,
    },
    BootChange {
        led: 85,
        velocity: 0,
    },
    BootChange {
        led: 24,
        velocity: 0,
    },
    BootChange {
        led: 24,
        velocity: 9,
    },
    BootChange {
        led: 75,
        velocity: 0,
    },
    BootChange {
        led: 75,
        velocity: 9,
    },
    BootChange {
        led: 21,
        velocity: 0,
    },
    BootChange {
        led: 21,
        velocity: 5,
    },
    BootChange {
        led: 78,
        velocity: 0,
    },
    BootChange {
        led: 78,
        velocity: 5,
    },
    BootChange {
        led: 51,
        velocity: 0,
    },
    BootChange {
        led: 51,
        velocity: 6,
    },
    BootChange {
        led: 48,
        velocity: 0,
    },
    BootChange {
        led: 48,
        velocity: 6,
    },
    BootChange {
        led: 32,
        velocity: 3,
    },
    BootChange {
        led: 81,
        velocity: 0,
    },
    BootChange {
        led: 81,
        velocity: 7,
    },
    BootChange {
        led: 18,
        velocity: 0,
    },
    BootChange {
        led: 18,
        velocity: 7,
    },
    BootChange {
        led: 67,
        velocity: 3,
    },
    BootChange {
        led: 62,
        velocity: 0,
    },
    BootChange {
        led: 62,
        velocity: 13,
    },
    BootChange {
        led: 84,
        velocity: 0,
    },
    BootChange {
        led: 15,
        velocity: 0,
    },
    BootChange {
        led: 37,
        velocity: 0,
    },
    BootChange {
        led: 37,
        velocity: 13,
    },
    BootChange {
        led: 74,
        velocity: 0,
    },
    BootChange {
        led: 74,
        velocity: 9,
    },
    BootChange {
        led: 25,
        velocity: 0,
    },
    BootChange {
        led: 25,
        velocity: 9,
    },
    BootChange {
        led: 22,
        velocity: 0,
    },
    BootChange {
        led: 22,
        velocity: 5,
    },
    BootChange {
        led: 77,
        velocity: 0,
    },
    BootChange {
        led: 77,
        velocity: 5,
    },
    BootChange {
        led: 41,
        velocity: 0,
    },
    BootChange {
        led: 41,
        velocity: 6,
    },
    BootChange {
        led: 58,
        velocity: 0,
    },
    BootChange {
        led: 58,
        velocity: 6,
    },
    BootChange {
        led: 33,
        velocity: 3,
    },
    BootChange {
        led: 71,
        velocity: 0,
    },
    BootChange {
        led: 71,
        velocity: 7,
    },
    BootChange {
        led: 28,
        velocity: 0,
    },
    BootChange {
        led: 28,
        velocity: 7,
    },
    BootChange {
        led: 66,
        velocity: 3,
    },
    BootChange {
        led: 52,
        velocity: 0,
    },
    BootChange {
        led: 52,
        velocity: 13,
    },
    BootChange {
        led: 83,
        velocity: 0,
    },
    BootChange {
        led: 16,
        velocity: 0,
    },
    BootChange {
        led: 47,
        velocity: 0,
    },
    BootChange {
        led: 47,
        velocity: 13,
    },
    BootChange {
        led: 73,
        velocity: 0,
    },
    BootChange {
        led: 73,
        velocity: 9,
    },
    BootChange {
        led: 26,
        velocity: 0,
    },
    BootChange {
        led: 26,
        velocity: 9,
    },
    BootChange {
        led: 23,
        velocity: 0,
    },
    BootChange {
        led: 23,
        velocity: 5,
    },
    BootChange {
        led: 76,
        velocity: 0,
    },
    BootChange {
        led: 76,
        velocity: 5,
    },
    BootChange {
        led: 31,
        velocity: 0,
    },
    BootChange {
        led: 31,
        velocity: 6,
    },
    BootChange {
        led: 68,
        velocity: 0,
    },
    BootChange {
        led: 68,
        velocity: 6,
    },
    BootChange {
        led: 61,
        velocity: 0,
    },
    BootChange {
        led: 38,
        velocity: 0,
    },
    BootChange {
        led: 34,
        velocity: 3,
    },
    BootChange {
        led: 61,
        velocity: 7,
    },
    BootChange {
        led: 38,
        velocity: 7,
    },
    BootChange {
        led: 65,
        velocity: 3,
    },
    BootChange {
        led: 42,
        velocity: 0,
    },
    BootChange {
        led: 42,
        velocity: 13,
    },
    BootChange {
        led: 82,
        velocity: 0,
    },
    BootChange {
        led: 17,
        velocity: 0,
    },
    BootChange {
        led: 57,
        velocity: 0,
    },
    BootChange {
        led: 57,
        velocity: 13,
    },
    BootChange {
        led: 72,
        velocity: 0,
    },
    BootChange {
        led: 72,
        velocity: 9,
    },
    BootChange {
        led: 27,
        velocity: 0,
    },
    BootChange {
        led: 27,
        velocity: 9,
    },
    BootChange {
        led: 24,
        velocity: 0,
    },
    BootChange {
        led: 24,
        velocity: 5,
    },
    BootChange {
        led: 75,
        velocity: 0,
    },
    BootChange {
        led: 75,
        velocity: 5,
    },
    BootChange {
        led: 21,
        velocity: 0,
    },
    BootChange {
        led: 21,
        velocity: 6,
    },
    BootChange {
        led: 78,
        velocity: 0,
    },
    BootChange {
        led: 78,
        velocity: 6,
    },
    BootChange {
        led: 51,
        velocity: 0,
    },
    BootChange {
        led: 51,
        velocity: 7,
    },
    BootChange {
        led: 64,
        velocity: 3,
    },
    BootChange {
        led: 35,
        velocity: 3,
    },
    BootChange {
        led: 48,
        velocity: 0,
    },
    BootChange {
        led: 48,
        velocity: 7,
    },
    BootChange {
        led: 32,
        velocity: 0,
    },
    BootChange {
        led: 32,
        velocity: 13,
    },
    BootChange {
        led: 81,
        velocity: 0,
    },
    BootChange {
        led: 18,
        velocity: 0,
    },
    BootChange {
        led: 67,
        velocity: 0,
    },
    BootChange {
        led: 67,
        velocity: 13,
    },
    BootChange {
        led: 62,
        velocity: 0,
    },
    BootChange {
        led: 62,
        velocity: 9,
    },
    BootChange {
        led: 37,
        velocity: 0,
    },
    BootChange {
        led: 37,
        velocity: 9,
    },
    BootChange {
        led: 74,
        velocity: 0,
    },
    BootChange {
        led: 74,
        velocity: 5,
    },
    BootChange {
        led: 25,
        velocity: 0,
    },
    BootChange {
        led: 25,
        velocity: 5,
    },
    BootChange {
        led: 22,
        velocity: 0,
    },
    BootChange {
        led: 22,
        velocity: 6,
    },
    BootChange {
        led: 77,
        velocity: 0,
    },
    BootChange {
        led: 77,
        velocity: 6,
    },
    BootChange {
        led: 41,
        velocity: 0,
    },
    BootChange {
        led: 41,
        velocity: 7,
    },
    BootChange {
        led: 63,
        velocity: 3,
    },
    BootChange {
        led: 36,
        velocity: 3,
    },
    BootChange {
        led: 58,
        velocity: 0,
    },
    BootChange {
        led: 58,
        velocity: 7,
    },
    BootChange {
        led: 33,
        velocity: 0,
    },
    BootChange {
        led: 33,
        velocity: 13,
    },
    BootChange {
        led: 71,
        velocity: 0,
    },
    BootChange {
        led: 28,
        velocity: 0,
    },
    BootChange {
        led: 66,
        velocity: 0,
    },
    BootChange {
        led: 66,
        velocity: 13,
    },
    BootChange {
        led: 52,
        velocity: 0,
    },
    BootChange {
        led: 52,
        velocity: 9,
    },
    BootChange {
        led: 47,
        velocity: 0,
    },
    BootChange {
        led: 47,
        velocity: 9,
    },
    BootChange {
        led: 73,
        velocity: 0,
    },
    BootChange {
        led: 73,
        velocity: 5,
    },
    BootChange {
        led: 26,
        velocity: 0,
    },
    BootChange {
        led: 26,
        velocity: 5,
    },
    BootChange {
        led: 23,
        velocity: 0,
    },
    BootChange {
        led: 23,
        velocity: 6,
    },
    BootChange {
        led: 76,
        velocity: 0,
    },
    BootChange {
        led: 76,
        velocity: 6,
    },
    BootChange {
        led: 31,
        velocity: 0,
    },
    BootChange {
        led: 31,
        velocity: 7,
    },
    BootChange {
        led: 53,
        velocity: 3,
    },
    BootChange {
        led: 46,
        velocity: 3,
    },
    BootChange {
        led: 68,
        velocity: 0,
    },
    BootChange {
        led: 68,
        velocity: 7,
    },
    BootChange {
        led: 34,
        velocity: 0,
    },
    BootChange {
        led: 34,
        velocity: 13,
    },
    BootChange {
        led: 61,
        velocity: 0,
    },
    BootChange {
        led: 38,
        velocity: 0,
    },
    BootChange {
        led: 65,
        velocity: 0,
    },
    BootChange {
        led: 65,
        velocity: 13,
    },
    BootChange {
        led: 42,
        velocity: 0,
    },
    BootChange {
        led: 42,
        velocity: 9,
    },
    BootChange {
        led: 57,
        velocity: 0,
    },
    BootChange {
        led: 57,
        velocity: 9,
    },
    BootChange {
        led: 72,
        velocity: 0,
    },
    BootChange {
        led: 72,
        velocity: 5,
    },
    BootChange {
        led: 27,
        velocity: 0,
    },
    BootChange {
        led: 27,
        velocity: 5,
    },
    BootChange {
        led: 24,
        velocity: 0,
    },
    BootChange {
        led: 24,
        velocity: 6,
    },
    BootChange {
        led: 75,
        velocity: 0,
    },
    BootChange {
        led: 75,
        velocity: 6,
    },
    BootChange {
        led: 21,
        velocity: 0,
    },
    BootChange {
        led: 21,
        velocity: 7,
    },
    BootChange {
        led: 43,
        velocity: 3,
    },
    BootChange {
        led: 56,
        velocity: 3,
    },
    BootChange {
        led: 78,
        velocity: 0,
    },
    BootChange {
        led: 78,
        velocity: 7,
    },
    BootChange {
        led: 51,
        velocity: 0,
    },
    BootChange {
        led: 64,
        velocity: 0,
    },
    BootChange {
        led: 64,
        velocity: 13,
    },
    BootChange {
        led: 35,
        velocity: 0,
    },
    BootChange {
        led: 35,
        velocity: 13,
    },
    BootChange {
        led: 48,
        velocity: 0,
    },
    BootChange {
        led: 32,
        velocity: 0,
    },
    BootChange {
        led: 32,
        velocity: 9,
    },
    BootChange {
        led: 67,
        velocity: 0,
    },
    BootChange {
        led: 67,
        velocity: 9,
    },
    BootChange {
        led: 62,
        velocity: 0,
    },
    BootChange {
        led: 37,
        velocity: 0,
    },
    BootChange {
        led: 62,
        velocity: 5,
    },
    BootChange {
        led: 37,
        velocity: 5,
    },
    BootChange {
        led: 74,
        velocity: 0,
    },
    BootChange {
        led: 74,
        velocity: 6,
    },
    BootChange {
        led: 25,
        velocity: 0,
    },
    BootChange {
        led: 25,
        velocity: 6,
    },
    BootChange {
        led: 22,
        velocity: 0,
    },
    BootChange {
        led: 22,
        velocity: 7,
    },
    BootChange {
        led: 44,
        velocity: 3,
    },
    BootChange {
        led: 55,
        velocity: 3,
    },
    BootChange {
        led: 77,
        velocity: 0,
    },
    BootChange {
        led: 77,
        velocity: 7,
    },
    BootChange {
        led: 41,
        velocity: 0,
    },
    BootChange {
        led: 63,
        velocity: 0,
    },
    BootChange {
        led: 63,
        velocity: 13,
    },
    BootChange {
        led: 36,
        velocity: 0,
    },
    BootChange {
        led: 36,
        velocity: 13,
    },
    BootChange {
        led: 58,
        velocity: 0,
    },
    BootChange {
        led: 33,
        velocity: 0,
    },
    BootChange {
        led: 33,
        velocity: 9,
    },
    BootChange {
        led: 66,
        velocity: 0,
    },
    BootChange {
        led: 66,
        velocity: 9,
    },
    BootChange {
        led: 52,
        velocity: 0,
    },
    BootChange {
        led: 52,
        velocity: 5,
    },
    BootChange {
        led: 47,
        velocity: 0,
    },
    BootChange {
        led: 47,
        velocity: 5,
    },
    BootChange {
        led: 73,
        velocity: 0,
    },
    BootChange {
        led: 26,
        velocity: 0,
    },
    BootChange {
        led: 73,
        velocity: 6,
    },
    BootChange {
        led: 26,
        velocity: 6,
    },
    BootChange {
        led: 23,
        velocity: 0,
    },
    BootChange {
        led: 23,
        velocity: 7,
    },
    BootChange {
        led: 54,
        velocity: 3,
    },
    BootChange {
        led: 45,
        velocity: 3,
    },
    BootChange {
        led: 76,
        velocity: 0,
    },
    BootChange {
        led: 76,
        velocity: 7,
    },
    BootChange {
        led: 31,
        velocity: 0,
    },
    BootChange {
        led: 53,
        velocity: 0,
    },
    BootChange {
        led: 53,
        velocity: 13,
    },
    BootChange {
        led: 46,
        velocity: 0,
    },
    BootChange {
        led: 46,
        velocity: 13,
    },
    BootChange {
        led: 68,
        velocity: 0,
    },
    BootChange {
        led: 34,
        velocity: 0,
    },
    BootChange {
        led: 34,
        velocity: 9,
    },
    BootChange {
        led: 65,
        velocity: 0,
    },
    BootChange {
        led: 65,
        velocity: 9,
    },
    BootChange {
        led: 42,
        velocity: 0,
    },
    BootChange {
        led: 42,
        velocity: 5,
    },
    BootChange {
        led: 57,
        velocity: 0,
    },
    BootChange {
        led: 57,
        velocity: 5,
    },
    BootChange {
        led: 72,
        velocity: 0,
    },
    BootChange {
        led: 72,
        velocity: 6,
    },
    BootChange {
        led: 27,
        velocity: 0,
    },
    BootChange {
        led: 27,
        velocity: 6,
    },
    BootChange {
        led: 24,
        velocity: 0,
    },
    BootChange {
        led: 24,
        velocity: 7,
    },
    BootChange {
        led: 75,
        velocity: 0,
    },
    BootChange {
        led: 75,
        velocity: 7,
    },
    BootChange {
        led: 21,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 13,
    },
    BootChange {
        led: 56,
        velocity: 0,
    },
    BootChange {
        led: 56,
        velocity: 13,
    },
    BootChange {
        led: 78,
        velocity: 0,
    },
    BootChange {
        led: 64,
        velocity: 0,
    },
    BootChange {
        led: 64,
        velocity: 9,
    },
    BootChange {
        led: 35,
        velocity: 0,
    },
    BootChange {
        led: 35,
        velocity: 9,
    },
    BootChange {
        led: 32,
        velocity: 0,
    },
    BootChange {
        led: 67,
        velocity: 0,
    },
    BootChange {
        led: 32,
        velocity: 5,
    },
    BootChange {
        led: 67,
        velocity: 5,
    },
    BootChange {
        led: 62,
        velocity: 0,
    },
    BootChange {
        led: 62,
        velocity: 6,
    },
    BootChange {
        led: 37,
        velocity: 0,
    },
    BootChange {
        led: 37,
        velocity: 6,
    },
    BootChange {
        led: 74,
        velocity: 0,
    },
    BootChange {
        led: 74,
        velocity: 7,
    },
    BootChange {
        led: 25,
        velocity: 0,
    },
    BootChange {
        led: 25,
        velocity: 7,
    },
    BootChange {
        led: 22,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 13,
    },
    BootChange {
        led: 55,
        velocity: 0,
    },
    BootChange {
        led: 55,
        velocity: 13,
    },
    BootChange {
        led: 77,
        velocity: 0,
    },
    BootChange {
        led: 63,
        velocity: 0,
    },
    BootChange {
        led: 63,
        velocity: 9,
    },
    BootChange {
        led: 36,
        velocity: 0,
    },
    BootChange {
        led: 36,
        velocity: 9,
    },
    BootChange {
        led: 33,
        velocity: 0,
    },
    BootChange {
        led: 33,
        velocity: 5,
    },
    BootChange {
        led: 66,
        velocity: 0,
    },
    BootChange {
        led: 66,
        velocity: 5,
    },
    BootChange {
        led: 52,
        velocity: 0,
    },
    BootChange {
        led: 52,
        velocity: 6,
    },
    BootChange {
        led: 47,
        velocity: 0,
    },
    BootChange {
        led: 47,
        velocity: 6,
    },
    BootChange {
        led: 73,
        velocity: 0,
    },
    BootChange {
        led: 73,
        velocity: 7,
    },
    BootChange {
        led: 26,
        velocity: 0,
    },
    BootChange {
        led: 26,
        velocity: 7,
    },
    BootChange {
        led: 23,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 13,
    },
    BootChange {
        led: 45,
        velocity: 0,
    },
    BootChange {
        led: 45,
        velocity: 13,
    },
    BootChange {
        led: 76,
        velocity: 0,
    },
    BootChange {
        led: 53,
        velocity: 0,
    },
    BootChange {
        led: 53,
        velocity: 9,
    },
    BootChange {
        led: 46,
        velocity: 0,
    },
    BootChange {
        led: 46,
        velocity: 9,
    },
    BootChange {
        led: 34,
        velocity: 0,
    },
    BootChange {
        led: 34,
        velocity: 5,
    },
    BootChange {
        led: 65,
        velocity: 0,
    },
    BootChange {
        led: 65,
        velocity: 5,
    },
    BootChange {
        led: 42,
        velocity: 0,
    },
    BootChange {
        led: 42,
        velocity: 6,
    },
    BootChange {
        led: 57,
        velocity: 0,
    },
    BootChange {
        led: 57,
        velocity: 6,
    },
    BootChange {
        led: 72,
        velocity: 0,
    },
    BootChange {
        led: 72,
        velocity: 7,
    },
    BootChange {
        led: 27,
        velocity: 0,
    },
    BootChange {
        led: 27,
        velocity: 7,
    },
    BootChange {
        led: 24,
        velocity: 0,
    },
    BootChange {
        led: 75,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 9,
    },
    BootChange {
        led: 56,
        velocity: 0,
    },
    BootChange {
        led: 56,
        velocity: 9,
    },
    BootChange {
        led: 64,
        velocity: 0,
    },
    BootChange {
        led: 64,
        velocity: 5,
    },
    BootChange {
        led: 35,
        velocity: 0,
    },
    BootChange {
        led: 35,
        velocity: 5,
    },
    BootChange {
        led: 32,
        velocity: 0,
    },
    BootChange {
        led: 32,
        velocity: 6,
    },
    BootChange {
        led: 67,
        velocity: 0,
    },
    BootChange {
        led: 67,
        velocity: 6,
    },
    BootChange {
        led: 62,
        velocity: 0,
    },
    BootChange {
        led: 62,
        velocity: 7,
    },
    BootChange {
        led: 37,
        velocity: 0,
    },
    BootChange {
        led: 37,
        velocity: 7,
    },
    BootChange {
        led: 74,
        velocity: 0,
    },
    BootChange {
        led: 25,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 9,
    },
    BootChange {
        led: 55,
        velocity: 0,
    },
    BootChange {
        led: 55,
        velocity: 9,
    },
    BootChange {
        led: 63,
        velocity: 0,
    },
    BootChange {
        led: 63,
        velocity: 5,
    },
    BootChange {
        led: 36,
        velocity: 0,
    },
    BootChange {
        led: 36,
        velocity: 5,
    },
    BootChange {
        led: 33,
        velocity: 0,
    },
    BootChange {
        led: 33,
        velocity: 6,
    },
    BootChange {
        led: 66,
        velocity: 0,
    },
    BootChange {
        led: 66,
        velocity: 6,
    },
    BootChange {
        led: 52,
        velocity: 0,
    },
    BootChange {
        led: 47,
        velocity: 0,
    },
    BootChange {
        led: 52,
        velocity: 7,
    },
    BootChange {
        led: 47,
        velocity: 7,
    },
    BootChange {
        led: 73,
        velocity: 0,
    },
    BootChange {
        led: 26,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 9,
    },
    BootChange {
        led: 45,
        velocity: 0,
    },
    BootChange {
        led: 45,
        velocity: 9,
    },
    BootChange {
        led: 53,
        velocity: 0,
    },
    BootChange {
        led: 53,
        velocity: 5,
    },
    BootChange {
        led: 46,
        velocity: 0,
    },
    BootChange {
        led: 46,
        velocity: 5,
    },
    BootChange {
        led: 34,
        velocity: 0,
    },
    BootChange {
        led: 34,
        velocity: 6,
    },
    BootChange {
        led: 65,
        velocity: 0,
    },
    BootChange {
        led: 65,
        velocity: 6,
    },
    BootChange {
        led: 42,
        velocity: 0,
    },
    BootChange {
        led: 42,
        velocity: 7,
    },
    BootChange {
        led: 57,
        velocity: 0,
    },
    BootChange {
        led: 57,
        velocity: 7,
    },
    BootChange {
        led: 72,
        velocity: 0,
    },
    BootChange {
        led: 27,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 5,
    },
    BootChange {
        led: 56,
        velocity: 0,
    },
    BootChange {
        led: 56,
        velocity: 5,
    },
    BootChange {
        led: 64,
        velocity: 0,
    },
    BootChange {
        led: 64,
        velocity: 6,
    },
    BootChange {
        led: 35,
        velocity: 0,
    },
    BootChange {
        led: 35,
        velocity: 6,
    },
    BootChange {
        led: 32,
        velocity: 0,
    },
    BootChange {
        led: 32,
        velocity: 7,
    },
    BootChange {
        led: 67,
        velocity: 0,
    },
    BootChange {
        led: 67,
        velocity: 7,
    },
    BootChange {
        led: 62,
        velocity: 0,
    },
    BootChange {
        led: 37,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 5,
    },
    BootChange {
        led: 55,
        velocity: 0,
    },
    BootChange {
        led: 55,
        velocity: 5,
    },
    BootChange {
        led: 63,
        velocity: 0,
    },
    BootChange {
        led: 63,
        velocity: 6,
    },
    BootChange {
        led: 36,
        velocity: 0,
    },
    BootChange {
        led: 36,
        velocity: 6,
    },
    BootChange {
        led: 33,
        velocity: 0,
    },
    BootChange {
        led: 33,
        velocity: 7,
    },
    BootChange {
        led: 66,
        velocity: 0,
    },
    BootChange {
        led: 66,
        velocity: 7,
    },
    BootChange {
        led: 52,
        velocity: 0,
    },
    BootChange {
        led: 47,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 5,
    },
    BootChange {
        led: 45,
        velocity: 0,
    },
    BootChange {
        led: 45,
        velocity: 5,
    },
    BootChange {
        led: 53,
        velocity: 0,
    },
    BootChange {
        led: 53,
        velocity: 6,
    },
    BootChange {
        led: 46,
        velocity: 0,
    },
    BootChange {
        led: 46,
        velocity: 6,
    },
    BootChange {
        led: 34,
        velocity: 0,
    },
    BootChange {
        led: 34,
        velocity: 7,
    },
    BootChange {
        led: 65,
        velocity: 0,
    },
    BootChange {
        led: 65,
        velocity: 7,
    },
    BootChange {
        led: 42,
        velocity: 0,
    },
    BootChange {
        led: 57,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 6,
    },
    BootChange {
        led: 56,
        velocity: 0,
    },
    BootChange {
        led: 56,
        velocity: 6,
    },
    BootChange {
        led: 64,
        velocity: 0,
    },
    BootChange {
        led: 64,
        velocity: 7,
    },
    BootChange {
        led: 35,
        velocity: 0,
    },
    BootChange {
        led: 35,
        velocity: 7,
    },
    BootChange {
        led: 32,
        velocity: 0,
    },
    BootChange {
        led: 67,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 0,
    },
    BootChange {
        led: 55,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 6,
    },
    BootChange {
        led: 55,
        velocity: 6,
    },
    BootChange {
        led: 63,
        velocity: 0,
    },
    BootChange {
        led: 63,
        velocity: 7,
    },
    BootChange {
        led: 36,
        velocity: 0,
    },
    BootChange {
        led: 36,
        velocity: 7,
    },
    BootChange {
        led: 33,
        velocity: 0,
    },
    BootChange {
        led: 66,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 6,
    },
    BootChange {
        led: 45,
        velocity: 0,
    },
    BootChange {
        led: 45,
        velocity: 6,
    },
    BootChange {
        led: 53,
        velocity: 0,
    },
    BootChange {
        led: 53,
        velocity: 7,
    },
    BootChange {
        led: 46,
        velocity: 0,
    },
    BootChange {
        led: 46,
        velocity: 7,
    },
    BootChange {
        led: 34,
        velocity: 0,
    },
    BootChange {
        led: 65,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 7,
    },
    BootChange {
        led: 56,
        velocity: 0,
    },
    BootChange {
        led: 56,
        velocity: 7,
    },
    BootChange {
        led: 64,
        velocity: 0,
    },
    BootChange {
        led: 35,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 7,
    },
    BootChange {
        led: 55,
        velocity: 0,
    },
    BootChange {
        led: 55,
        velocity: 7,
    },
    BootChange {
        led: 63,
        velocity: 0,
    },
    BootChange {
        led: 36,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 7,
    },
    BootChange {
        led: 45,
        velocity: 0,
    },
    BootChange {
        led: 45,
        velocity: 7,
    },
    BootChange {
        led: 53,
        velocity: 0,
    },
    BootChange {
        led: 46,
        velocity: 0,
    },
    BootChange {
        led: 43,
        velocity: 0,
    },
    BootChange {
        led: 56,
        velocity: 0,
    },
    BootChange {
        led: 44,
        velocity: 0,
    },
    BootChange {
        led: 55,
        velocity: 0,
    },
    BootChange {
        led: 54,
        velocity: 0,
    },
    BootChange {
        led: 45,
        velocity: 0,
    },
];
